/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "CumTwit.h"

bool_t
xdr_mensaje (XDR *xdrs, mensaje *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX_CAD))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usuario (XDR *xdrs, usuario *objp)
{
	register int32_t *buf;

	 if (!xdr_usuario_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cadena (XDR *xdrs, cadena *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 50))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_credenciales (XDR *xdrs, credenciales *objp)
{
	register int32_t *buf;

	 if (!xdr_credenciales_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paquete (XDR *xdrs, paquete *objp)
{
	register int32_t *buf;

	 if (!xdr_paquete_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buscador (XDR *xdrs, buscador *objp)
{
	register int32_t *buf;

	 if (!xdr_buscador_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lista (XDR *xdrs, lista *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo), (xdrproc_t) xdr_nodo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buscador_t (XDR *xdrs, buscador_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->login))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->login_buscado))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->fecha))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paquete_t (XDR *xdrs, paquete_t *objp)
{
	register int32_t *buf;

	 if (!xdr_mensaje (xdrs, &objp->mess))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->dest))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->remite))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->fecha))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->hora))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_usuario_t (XDR *xdrs, usuario_t *objp)
{
	register int32_t *buf;

	 if (!xdr_cadena (xdrs, &objp->login))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->nombre))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->apellido))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->passwd))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->ciudad))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->pais))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->fecha))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_credenciales_t (XDR *xdrs, credenciales_t *objp)
{
	register int32_t *buf;

	 if (!xdr_cadena (xdrs, &objp->login))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->passwd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo (XDR *xdrs, nodo *objp)
{
	register int32_t *buf;

	 if (!xdr_paquete (xdrs, &objp->info))
		 return FALSE;
	 if (!xdr_lista (xdrs, &objp->siguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_res_busqueda (XDR *xdrs, res_busqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_lista (xdrs, &objp->res_busqueda_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
